### ISSUE TITLE
Playlist, connection, metadata, CPU usage.

### ISSUE THREAD

**Issue by simahawk** [edne/shouty#6]
Hello,

I'm wondering if I can handle my use case w/ this lib (w/ some glue code of course).

I'm looking for a lighter replacement for liquidsoap as it does too much and I only need to play a playlist + idv3 tags on each file holding metadata.

**Questions:**

1. code tells me that a connection is meant to work w/ one single file
a. open 1 connection per file when you have 100 files is still ok? (well, they get closed by ctx manager indeed, still... :))
b. should  I open only one connection and attach metadata on the fly on current connection?

2. CPU usage. Judging from your experience (I know the lib is not that old): are they any issue I might encounter w/ one of the above options?

Thanks in advance!

**Comment by turlando** [comment]
1. a. When you close a connection the streaming will end. If you want to provide a continuous streaming through Icecast you must `send()` your files from within the same connection. [Here](https://github.com/turlando/airhead/blob/master/airhead/broadcaster.py) you can find a real-world usage example (yet maybe ugly and outdated).

1. b. If you want to stream Ogg Vorbis then you're fine. When you switch to a different track Icecast will take care of updating the stream with the new metadata. Just make sure that the files you're streaming have the same channels, sample rate, bitrate (@edne maybe we should note this in the documentation?). If you want to stream MP3 you must explicitly specify the new metadata from your code. AFAIK the code for that feature has not been written and actually this library has never been tested against MP3. [Here](https://www.aelius.com/njh/libshout-doc/libshout.html#id2499325) is further documentation.

2. I don't know but it should not be much more than what libshout requires. Just try it and see :)

**Comment by simahawk** [comment]
yeah, MP3 here... I'll give a try to ogg anyway. Thanks for the pointers!

BTW, wow, that `airhead` lib is kind of what I was planning to achieve in the long term. I'll have a look at it.

**Comment by turlando** [comment]
Well, I'm currently considering to ditch the Icecast integration for a built-in solution.

**Comment by simahawk** [comment]
may I ask you what's your plan on this? I've looked around but I didn't find any real viable open-source solution.

**Comment by turlando** [comment]
As far as I know there is nothing like that and I'm planning to write my own Ogg parser and streamer.

**Comment by simahawk** [comment]
@turlando @edne I got a raw prototype working. I'm running this piece of code https://gist.github.com/simahawk/434569cf76eeca504ec80e131d12edc6
in a docker container (that's why I dropped threading). It works smoothly beside this:
```
$ docker-compose run --rm xshouty --playlist=/radio/playlists/foo/playlist.m3u --mount=foo2
SEND
Exception in thread Thread-1:
Traceback (most recent call last):
  File "/usr/lib/python3.4/threading.py", line 920, in _bootstrap_inner
    self.run()
  File "/opt/xshouty/broadcaster.py", line 54, in run
    with shouty.connect(**self._params) as connection:
  File "/usr/lib/python3.4/contextlib.py", line 59, in __enter__
    return next(self.gen)
  File "/usr/local/lib/python3.4/dist-packages/shouty/utils.py", line 8, in connect
    cn.open()
  File "/usr/local/lib/python3.4/dist-packages/shouty/connection.py", line 32, in decorated
    err_name, err_str))
Exception: Failed open
Error code: NOLOGIN
Error description: Login failed
```
which sounds strange as the streaming is working on icecast. Same result if running pure python.
Before I dig into it... any pointer?

BTW: resources usage is waaaaaaaaaaaay much lower than liquidsoap, not even comparable indeed.  :)

**Comment by FriendlyAI** [comment]
I've been trying to implement the metadata/currently playing function using this shouty library, but I can't seem to get it to work. I've read the documentation [here](https://www.aelius.com/njh/libshout-doc/libshout.html#id2499325) and looked at the outdated python bindings for libshout [here](https://pypi.org/project/python-shout/), and it doesn't seem like too hard of a task. The basic structure in python seems to be this:
```
# Allocate memory for new metadata structure
metadata = lib.shout_metadata_new()

# Add 'song': '<song name>' metadata attribute
lib.shout_metadata_add.argtypes = [c_void_p, c_char_p, c_char_p]
lib.shout_metadata_add(metadata, 
                       'song'.encode('ascii'), 
                       '<song name>'.encode('ascii'))  # Segmentation fault here

# Set metadata to stream
lib.shout_set_metadata(self.obj, metadata)

# Free memory when done
lib.shout_metadata_free(metadata)
```
Running this code just results in python crashing with ```exit code 139 (interrupted by signal 11: SIGSEGV)``` on the ```shout_metadata_add()``` call.
Unfortunately, I don't have any background in C, so I'm not sure exactly where the segfault is coming from. The basic structure of updating metadata for MP3 streams doesn't seem more complicated than this though, so I'm sure I'm just missing something minor. Any idea what might be wrong?
